spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/carrera?serverTimezone=UTC"
    username: root
    password: Linkuei2
  jpa:
    hibernate:
      ddl-auto: none